name: TS101 Build

on:
  push:
    branches: [ts101-build1]
  pull_request:

jobs:
  build-ts101:
    runs-on: ubuntu-22.04
    container:
      image: alpine:3.19

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install deps
        run: apk add --no-cache gcc-arm-none-eabi g++-arm-none-eabi newlib-arm-none-eabi findutils python3 py3-pip make git bash

      - name: Python deps
        run: python3 -m pip install --break-system-packages bdflib

      - name: Build TS101 (EN)
        run: make -C source firmware-EN model=TS101

      - name: Copy licenses
        run: cp LICENSE scripts/LICENSE_RELEASE.md source/Hexfile/

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: TS101-Firmware
          path: source/Hexfile/TS101_*
